run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - generated
  skip-files:
    - ".*_gen.go"

linters-settings:
  errcheck:
    check-type-assertions: true

  govet:
    check-shadowing: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-checks:
      - captLocal
      - ifElseChain
      - sloppyLen
      - rangeValCopy
      - appendAssign

  revive:
    severity: warning
    confidence: 0.8
    rules:
      - name: indent-error-flow
      - name: var-naming
      - name: import-shadowing
      - name: line-length-limit
        arguments: [140]
      - name: cognitive-complexity
        arguments: [20]

  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - gofmt
    - goimports
    - gocyclo
    - nakedret
    - dupl
    - goconst
    - gocritic
  disable:
    - maligned     # artık kullanılmıyor
    - scopelint    # deprecated, revive yerine kullanılıyor

output:
  format: colored-line-number
  print-issued-lines: true
  sort-results: true 
