version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: codesentinel-db
    environment:
      POSTGRES_DB: ai_codeguard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: codesentinel-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: 
